pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                sh 'docker run -t postman/newman_ubuntu1404 run https://www.getpostman.com/collections/8a0c9bc08f062d12dcda'
            }
        }
    }
}